insert into categories (category_name) values('Fashion');
insert into categories (category_name) values('Electronics');
insert into categories (category_name) values('Books');
insert into categories (category_name) values('Groceries');
insert into categories (category_name) values('Medicines');
insert into roles(role) values ('consumer');
insert into roles(role) values ('seller');
insert into users (user_name, password) values('jack', 'pass_word');
insert into users (user_name, password) values('bob', 'pass_word');
insert into users (user_name, password) values('apple', 'pass_word');
insert into users (user_name, password) values('glaxo', 'pass_word');
insert into cart(total_Amount, user_id) values (20, 1);
insert into cart(total_Amount, user_id) values (0, 2);
insert into user_role(user_id, role_id) values (1, 1);
insert into user_role(user_id, role_id) values (2, 1);
insert into user_role(user_id, role_id) values (3, 2);
insert into user_role(user_id, role_id) values (4, 2);
insert into products(price, product_name, category_id, seller_id) values(29190, 'Apple iPad 10.2 8th Gne WiFi iOS Tablet', 2, 3);
insert into products(price, product_name, category_id, seller_id) values(10, 'Cronin pain relief tablet', 5, 4);
insert into cart_products(cart_id, product_id, quantity) values (1, 2, 2);
